<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button</name>
   <tag></tag>
   <elementGuidId>c19c1d5e-cbe4-48e8-bf06-eac50768544e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;enter-online-id-submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='enter-online-id-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66c22f61-0196-4621-b511-54113ebfbb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>92f66144-2bd3-4d06-90a0-9f0aeaddf52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enterOnlineIDFormSubmit();</value>
      <webElementGuid>d994e1e6-df3a-4a75-bbcb-f2780e1f6926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1beb91f-4895-4f14-adee-bb0f9f85b3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>80f8a1be-527b-40db-bff3-59430fbee49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-bofa btn-bofa-blue btn-bofa-small btn-bofa-noRight</value>
      <webElementGuid>c358a4dd-7d49-4db8-9197-9a86eab6dddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enter-online-id-submit</value>
      <webElementGuid>d951eb35-e6e1-4e84-8f77-75a59528c37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>5ec42689-a9f6-487a-a4de-aa31573bee8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EnterOnlineIDForm&quot;)/a[@class=&quot;btn-bofa btn-bofa-blue btn-bofa-small btn-bofa-noRight&quot;]</value>
      <webElementGuid>4548959b-9f62-4cee-b991-637745e4df75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='enter-online-id-submit']</value>
      <webElementGuid>6e254533-523f-48b8-991f-606314c87afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EnterOnlineIDForm']/a[2]</value>
      <webElementGuid>97defdfb-6c46-443c-9144-2cfa2c80c5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your Password?'])[1]/following::a[1]</value>
      <webElementGuid>dfb76935-b403-4c3b-9fa2-65a955d8cb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='is unavailable. Please enter atleast 6 characters of online id to enable Passcode'])[1]/following::a[2]</value>
      <webElementGuid>990c71ad-e717-45a9-9110-8a8c39c66ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In with mobile app'])[1]/preceding::a[1]</value>
      <webElementGuid>f4b12c38-8acf-4abe-a4a3-a14eceb481f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>19d6e7d8-b001-42a6-8241-82d52939eab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>a23226c8-e91e-4f2e-ae15-ad428c5eb844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = 'Log In' and @name = 'enter-online-id-submit' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>2004e29c-9873-4b66-a1b0-db2840c2dc7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
