<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paswd</name>
   <tag></tag>
   <elementGuidId>8bec05fa-4dbb-4d5e-9f74-22b60f8ab1a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tlpvt-passcode-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tlpvt-passcode-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>836ccc34-e03e-49ab-9031-8a88ad61451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ec9fe745-7b5e-4260-9781-f622c8821b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tl-private fl-lt</value>
      <webElementGuid>7b3bc8f8-eff6-43da-a02b-63f6c2a0bf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tlpvt-passcode-input</value>
      <webElementGuid>cc6ae9e8-890d-46a8-a2a0-d5a1e9cec590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dummy-passcode</value>
      <webElementGuid>e9a84d30-f1bb-4349-bd84-cd463059a4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f967b45e-f0a9-4218-9213-ca6f0149c9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a5d376a3-2e68-4848-8000-853b53caa35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7db83c98-82e7-45b2-b55d-653516f61b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tlpvt-passcode-input&quot;)</value>
      <webElementGuid>f53e8a79-3eca-4727-a88e-bc19f267999b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tlpvt-passcode-input']</value>
      <webElementGuid>7556bbc4-0cfc-42fc-a7ac-1427f1fb68de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EnterOnlineIDForm']/div[2]/input</value>
      <webElementGuid>3995b8f6-53be-4a4c-b447-ae5da40e48a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>81cd4d50-b5ef-4262-a8ec-54da56cdd565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'tlpvt-passcode-input' and @name = 'dummy-passcode']</value>
      <webElementGuid>7883e959-236d-4a69-8dc1-605dd01c8d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
