<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username</name>
   <tag></tag>
   <elementGuidId>d457906a-b01b-4081-98c4-0bd2dbbcc520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enterID-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='enterID-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be90bdb2-9b7e-47d9-adf7-4fdff69a698a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23073e0c-ad1c-43b4-aa35-e737b2ba6f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enterID-input</value>
      <webElementGuid>1379acc2-3797-4129-9939-409214f7ca6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dummy-onlineId</value>
      <webElementGuid>d253c812-8c59-4c21-bf12-0ac8e35267b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>8d5251c9-b52e-47e7-96b3-415a5a229125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d2563d7-c978-4821-aabc-cc77ab4f5d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enterID-input&quot;)</value>
      <webElementGuid>61e8b8e7-5558-4162-af7c-f40424d1e3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='enterID-input']</value>
      <webElementGuid>7e8a700e-5b80-486e-ac2e-b44c095e5cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='EnterOnlineIDForm']/div/input[10]</value>
      <webElementGuid>b77c289e-b4be-4d71-91be-848109a6b4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>f446bd8d-1c36-45d1-bd1f-ebfcf2efd5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'enterID-input' and @name = 'dummy-onlineId']</value>
      <webElementGuid>ff03eb8b-a5f2-4fc7-a536-7098a874c540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
